name: my-web-ci-cd

on: [push, pull_request]

jobs:
    all:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                threads:
                    - '4'
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Install Depedencies
              run: make install

            - name: Run Linter
              run: make lint

            - name: Run Typecheck
              run: make typecheck

            - name: Run Format Check
              run: make format-check

            - name: Run Tests
              run: |
                  make test
                  rm -rf __tests__

            - name: Run Build
              # just to ensure build dont fail due to absence of env variable
              # the real env will be used somewhere else
              env:
                  NODE_ENV: production
                  EMAIL: email
                  PASS: pass
                  ORIGIN: origin
                  PUBLIC_URL: publicURL
              run: make build

            - name: Run Clean Up
              run: make clean-up
